name = "hudi-pages-submission"
main = "src/index.ts"
compatibility_date = "2026-07-01"

[vars]
ALLOWED_ORIGIN = "https://coletivo-inspira.github.io"
GITHUB_ORG = "coletivo-inspira"
GITHUB_REPOSITORY = "hudi-pg"

